version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./dockerfile
    environment:
      - VUE_APP_CLOUD_URL=${CENTRAL_ADDRESS}
      - VUE_APP_EDGE_URL=http://localhost:5000
    ports:
      - "8080:8080"
    links:
      - "edge-server:edge"
  edge-server:
    container_name: edge-server
    environment:
      - central_address=${CENTRAL_ADDRESS}
    build: ./backend
    ports:
      - "5000:5000"
