version: "3.9"
services:
  frontend:
    container_name: frontend
    image: natthanonm/sds-edge-computing-frontend:latest
    environment:
      - VUE_APP_CLOUD_URL=${CENTRAL_ADDRESS}
      - VUE_APP_EDGE_URL=http://localhost:50000
    ports:
      - "8080:8080"
  edge-server:
    container_name: edge-server
    image: natthanonm/sds-edge-computing-edge-server:latest
    environment:
      - central_address=${CENTRAL_ADDRESS}
    ports:
      - "50000:5000"
